AWSAccountID: "751021557844"
App: "HalappOrder"
Environment: PRODUCTION
Region: eu-central-1

ShouldCreateDynamoOrderDB: "true"
OrderDBName: HalOrder

UserPoolID: eu-central-1_a1Vy48gOr
UserPoolClientID: 5g536qr72pjrt49saqb64jtedt